core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include('dynamo_blogger.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dynamo_blogger/urls.py
from django.urls import path
from dynamo_blogger import views


app_name = "dynamo_blogger"


urlpatterns = [
    path("", views.home__page, name="home__page"),
    path("<slug>/", views.blog__post, name="blog__post"),
    path("comment/<slug>/", views.create__comment, name="blog__comment"),
    path("category/<slug>/", views.category__page, name="category__page"),
]

dynamo_blogger/models.py
from django.utils.text import slugify
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.contrib.auth import get_user_model
from dynamo_blogger.helpers.timestamps import TimeStampedModel


User = get_user_model()


class Category(TimeStampedModel):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True, editable=False)
    
    class Meta:
        verbose_name_plural = "Blog Categories"
        db_table = "blog_categories"
        
    def __str__(self) -> str:
        return self.slug
    
    def get_absolute_url(self):
        return reverse("dynamo_blogger:category__page", args=[self.slug])
    
    
    def save(self, *args, **kwargs):
        
        if not self.slug:
            self.slug = slugify(self.title)
            super(Category, self).save(*args, **kwargs)
        super(Category, self).save(*args, **kwargs)

    
class PostAuthor(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to="author_images/", null=True, blank=True)
    biography = RichTextField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    
    class Meta:
        verbose_name_plural = "Blog Authors"
        db_table = "blog_authors"
    
    def __str__(self) -> str:
        return "{} {}".format(self.user.first_name, self.user.last_name)
    
    def fullname(self) -> str:
        return "{} {}".format(self.user.first_name, self.user.last_name)
        

class Post(TimeStampedModel):
    STATUS_TYPES = (
        ("draft", "draft"),
        ("published", "published"),
        ("in-review", "in-review"),
        ("rejected", "rejected"),
    )
    
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True, editable=False)
    image = models.ImageField(upload_to="post_images/", null=True, blank=True)
    tag = models.ForeignKey(Category, null=True, blank=True, on_delete=models.DO_NOTHING)
    description = RichTextField()
    featured = models.BooleanField(default=False)
    status = models.CharField(max_length=10, choices=STATUS_TYPES, default="draft")
    author = models.ForeignKey(PostAuthor, on_delete=models.CASCADE, null=True, blank=True)
    
    class Meta:
        verbose_name_plural = "Blog Posts"
        db_table = "blog_posts"
        
    def __str__(self) -> str:
        return "{}: {}".format(self.title, self.tag.slug)
    
    def save(self, *args, **kwargs):
        
        if not self.slug:
            self.slug = slugify(self.title)
            super(Post, self).save(*args, **kwargs)
        super(Post, self).save(*args, **kwargs)
        
    def get_absolute_url(self):
        return reverse("dynamo_blogger:blog__post", args=[self.slug])
         
    def get_number_of_comments(self):
        """
        It returns the number of comments associated with a post
        :return: The number of comments for a given post.
        """
        comment_count = Comment.objects.filter(blog_post_id=self.id).count()
        return comment_count
              
        
class Comment(TimeStampedModel):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    website = models.URLField(max_length=255)
    message = models.TextField(max_length=600)
    blog_post = models.ForeignKey(Post, blank=True, null=True, on_delete=models.CASCADE)
    reply_to = models.ForeignKey("self", blank=True, null=True, on_delete=models.SET_NULL)
    
    class Meta:
        verbose_name_plural = "Blog Comments"
        db_table = "blog_comments"
        
    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        super(Comment, self).save(*args, **kwargs)
    
    
class Newsletter(TimeStampedModel):
    email = models.EmailField()
    
    class Meta:
        verbose_name_plural = "Blog Newsletters"
        db_table = "blog_newsletters"
    
    def __str__(self) -> str:
        return self.email

dynamo_blogger/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from dynamo_blogger.models import Category, Newsletter, Post, Comment


def home__page(request:HttpRequest) -> HttpResponse:
    """
    > It returns a rendered template of the home page, 
    with the site name, social media links, and
    categories
    
    :param request: This is the request object that Django passes to the view
    :type request: HttpRequest
    :return: A HttpResponse object.
    """
    
    categories = Category.objects.all().order_by("date_created")
    
    # Get latest updated posts
    latest_posts = Post.objects.filter(status="published").order_by("date_updated")[:2]
    
    # Get recent created posts
    recent_posts = Post.objects.filter(status="published").order_by("date_created")[:6]
    
    # Get categories title 
    category_names = []
    
    # Append each category name to category_names list
    [category_names.append(category.slug) for category in categories]
    
    # Print category names to the terminal
    print("Category Names: ", category_names[2])
    
    # Get posts with different categories
    posts_1 = Post.objects.filter(tag__slug=category_names[0], status="published").order_by("date_created")[:1]
    posts_2 = Post.objects.filter(tag__slug=category_names[1], status="published").order_by("date_created")[:2]
    posts_3 = Post.objects.filter(tag__slug=category_names[2], status="published").order_by("date_created")[:2]
    posts_4 = Post.objects.filter(tag__slug=category_names[3], status="published").order_by("date_created")[:2]
    
    # Get featured posts
    featured_posts = Post.objects.filter(featured=True, status="published").order_by("date_created")[:3]
    
    # Most read featured posts
    most_read_posts = Post.objects.filter(featured=True, status="published").order_by("date_created")[:4]
    
    
    if request.method == "POST":
        email = request.POST.get("newsletter")
    
        # Create newsletter and save to database
        newsletter = Newsletter.objects.create(email=email)
        newsletter.save()
        
        # Redirect user to the home page with a response message
        messages.success(request, "You have been subscribed to our newsletter!")
        return redirect("dynamo_blogger:home__page")

    context = {
        "site__name": settings.DYNAMO_BLOGGER['site_name'],
        "facebook": settings.DYNAMO_BLOGGER['facebook'],
        "twitter": settings.DYNAMO_BLOGGER['twitter'],
        "linkedin": settings.DYNAMO_BLOGGER['linkedin'],
        "instagram": settings.DYNAMO_BLOGGER['instagram'],
        
        "latest_posts": latest_posts,
        "recent_posts": recent_posts,
        "posts_1": posts_1,
        "posts_2": posts_2,
        "posts_3": posts_3,
        "posts_4": posts_4,
        "featured_posts": featured_posts,
        "most_read_posts": most_read_posts,
        
        "categories": categories
    }
    return render(request, "blog/index.html", context)


def blog__post(request:HttpRequest, slug:str) -> HttpResponse:
    """
    > The function `blog__post` takes a request and a slug, 
    gets the most read posts, the category page and then renders them 
    to the home page (returns a response)
    
    :param request: The request object
    :type request: HttpRequest
    :param slug: The slug of the post to be displayed
    :type slug: str
    :return: A HttpResponse object.
    """
    
    try:
        post = Post.objects.get(slug=slug)
    except Post.DoesNotExist:
        post = None
    
    # Get featured posts
    featured_posts = Post.objects.filter(featured=True, status="published")\
        .order_by("date_created")[:2]
    
    # Most read featured posts
    most_read_posts = Post.objects.filter(featured=True, status="published")\
        .order_by("date_created")[:4]
    
    # User comments 
    comments = Comment.objects.filter(blog_post=post)
    
    categories = Category.objects.all().order_by("date_created")
    
    context = {
        "categories": categories,
        "post": post,
        
        "featured_posts": featured_posts,
        "most_read_posts": most_read_posts,
        
        "comments": comments,
        
        "site__name": settings.DYNAMO_BLOGGER['site_name'],
        "facebook": settings.DYNAMO_BLOGGER['facebook'],
        "twitter": settings.DYNAMO_BLOGGER['twitter'],
        "linkedin": settings.DYNAMO_BLOGGER['linkedin'],
        "instagram": settings.DYNAMO_BLOGGER['instagram'],
    }
    return render(request, "blog/blog-post.html", context)


def category__page(request:HttpRequest, slug:str) -> HttpResponse:
    """
    It gets the category from the database, 
    gets all the posts that belong to that category, gets the
    most read posts, the category page and then renders them 
    to the category page
    
    :param request: The request object
    :type request: HttpRequest
    :param slug: The slug of the category to be displayed
    :type slug: str
    :return: A HttpResponse object
    """

    category = Category.objects.get(slug=slug)
    
    categories = Category.objects.all().order_by("date_created")
    
    # Category posts
    posts = Post.objects.filter(tag=category, status="published")\
        .order_by("date_created")
    
    try:
        featured_post = Post.objects.get(tag=category, status="published", featured=True)
    except Post.DoesNotExist:
        featured_post = Post.objects.filter(tag=category, status="published").first()
        
    # Most read featured posts
    most_read_posts = Post.objects.filter(featured=True, status="published")\
        .order_by("date_created")[:4]
    
    
    context = {
        "categories": categories,
        "category": category,
        
        "most_read_posts": most_read_posts,
        "posts": posts,
        "featured_post": featured_post,
        
        "site__name": settings.DYNAMO_BLOGGER['site_name'],
        "facebook": settings.DYNAMO_BLOGGER['facebook'],
        "twitter": settings.DYNAMO_BLOGGER['twitter'],
        "linkedin": settings.DYNAMO_BLOGGER['linkedin'],
        "instagram": settings.DYNAMO_BLOGGER['instagram'],
    }
    return render(request, "blog/category.html", context)


def create__comment(request:HttpRequest, slug) -> HttpResponseRedirect:
    """
    > Create a comment object with the data from the form, 
    save it to the database, and redirect the
    user to the blog post page
    
    :param request: The request object that was sent to the view
    :type request: HttpRequest
    :param slug: The slug of the blog post that the comment is being created for
    :return: A redirect to the blog post page.
    """
    name = request.POST.get("name")
    email = request.POST.get("email")
    website = request.POST.get("website")
    message = request.POST.get("message")
    
    # Create comment and save to database
    comment = Comment.objects.create(
        name=name, email=email, website=website, 
        message=message, blog_post=Post.objects.get(slug=slug)
    )
    comment.save()
    return redirect("dynamo_blogger:blog__post", slug)

dynamo_blogger/templates/blog/blog-post.html
{% extends "base.html" %}

{% load static %}

{% block title %} 
{{ post.title }} 
{% endblock title %}

{% block content %}
<div class="section">

	<div class="container">

		<div class="row">

			<div class="col-md-8">
				<div class="section-row sticky-container">
					<div class="main-post">
						<h3>{{ post.title|upper }}</h3>
						
						<figure class="figure-img">
							<img class="img-responsive" src="{{ post.image.url }}" alt="{{ post.title }}">
						</figure>

						<p>{{ post.description|safe }}</p>
					</div>
					<div class="post-shares sticky-shares">
						<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" class="share-facebook"><i class="fa fa-facebook"></i></a>
						<a target="_blank" href="https://twitter.com/intent/tweet?text={{ post.title }}&url={{ request.build_absolute_uri }}" class="share-twitter"><i class="fa fa-twitter"></i></a>
						<a target="_blank" href="https://api.whatsapp.com/?text={{ post.title }}?url={{ request.build_absolute_uri }}" class="share-whatsapp"><i class="fa fa-whatsapp"></i></a>
						<a target="_blank" href="https://www.linkedin.com/shareArticle/?title={{ post.title }}&url={{ request.build_absolute_uri }}2F{{ post.title }}2F&mini=true" class="share-linkedin"><i class="fa fa-linkedin"></i></a>
					</div>
				</div>

				<hr>

				<div class="section-row">
					<div class="post-author">
						<div class="media">
							<div class="media-left">
								<img class="media-object author-pic" src="{{ post.author.profile_picture.url }}" alt="{{ post.author.user.username }}">
							</div>
							<div class="media-body">
								<div class="media-heading">
									<h3>{{ post.author.fullname }}</h3>
								</div>
								<p>
									{{ post.author.biography|safe }}
								</p>
								<ul class="author-social">
									<li><a href="{{ post.author.facebook }}" target="_blank"><i class="fa fa-facebook"></i></a></li>
									<li><a href="{{ post.author.twitter }}" target="_blank"><i class="fa fa-twitter"></i></a></li>
									<li><a href="{{ post.author.linkedin }}" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>


				<div class="section-row">
					<div class="section-title">
						<h2>{{ post.get_number_of_comments }} Comments</h2>
					</div>
					<div class="post-comments">

						{% for comment in comments %}
						<div class="media">
							<div class="media-left">
								<img class="media-object" src="{% static 'img/avatar.png' %}" alt="">
							</div>
							<div class="media-body">
								<div class="media-heading">
									<h4>{{ comment.name }}</h4>
									<span class="time">{{ comment.date_created }}</span>
									{% comment %} <a href="#" class="reply">Reply</a> {% endcomment %}
								</div>
								<p>
									{{ comment.message }}
								</p>

								{% comment %} <div class="media">
									<div class="media-left">
										<img class="media-object" src="{% static 'img/avatar.png' %}" alt="">
									</div>
									<div class="media-body">
										<div class="media-heading">
											<h4>John Doe</h4>
											<span class="time">March 27, 2018 at 8:00 am</span>
											<a href="#" class="reply">Reply</a>
										</div>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
											tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
											veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
											commodo consequat.</p>
									</div>
								</div> {% endcomment %}

							</div>
						</div>
						{% endfor %}

					</div>
				</div>


				<div class="section-row">
					<div class="section-title">
						<h2>Leave a reply</h2>
						<p>your email address will not be published. required fields are marked *</p>
					</div>
					<form method="POST" action="{% url 'dynamo_blogger:blog__comment' post.slug %}" class="post-reply">
						{% csrf_token %}
						
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<span>Name *</span>
									<input class="input" type="text" name="name" required>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<span>Email *</span>
									<input class="input" type="email" name="email" required>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<span>Website</span>
									<input class="input" type="text" name="website">
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<textarea class="input" name="message" placeholder="Message*" required></textarea>
								</div>
								<button class="primary-button">Submit</button>
							</div>
						</div>
					</form>
				</div>

			</div>


			<div class="col-md-4">

				<div class="aside-widget">
					<div class="section-title">
						<h2>Most Read</h2>
					</div>
					
					{% for post in most_read_posts %}
					<div class="post post-widget">
						<a class="post-img" href="{{ post.get_absolute_url }}">
							<img src="{{ post.image.url }}" alt="{{ post.title }}">
						</a>
						<div class="post-body">
							<h3 class="post-title">
								<a href="{{ post.get_absolute_url }}">
									{{ post.title }}
								</a>
							</h3>
						</div>
					</div>
					{% endfor %}

				</div>


				<div class="aside-widget">
					<div class="section-title">
						<h2>Featured Posts</h2>
					</div>
					
					{% for post in featured_posts %}
					<div class="post post-thumb">
						<a class="post-img" href="{{ post.get_absolute_url }}">
							<img src="{{ post.image.url }}" alt="{{ post.title }}">
						</a>
						
						<div class="post-body">
							<div class="post-meta">
								<a class="post-category cat-3" href="{{ post.tag.get_absolute_url }}">
									{{ post.tag.title }}
								</a>
								<span class="post-date">
									{{ post.date_created|date:"M d, Y" }}
								</span>
							</div>
							<h3 class="post-title">
								<a href="{{ post.get_absolute_url }}">
									{{ post.title }}
								</a>
							</h3>
						</div>
					</div>
					{% endfor %}

				</div>

			</div>

		</div>

	</div>

</div>
{% endblock content %}

dynamo_blogger/templates/blog/category.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  {{ category.title }}
{% endblock title %}

{% block content %}
	<div class="section">

		<div class="container">

			<div class="row">
				<div class="col-md-8">
					<div class="row">

						<div class="col-md-12">
							<div class="post post-thumb">
								<a class="post-img" href="{{ featured_post.get_absolute_url }}">
									<img src="{{ featured_post.image.url }}" alt="{{ featured_post.title }}">
								</a>
								
								<div class="post-body">
									<div class="post-meta">
										<a class="post-category cat-2" href="{{ featured_post.tag.get_absolute_url }}">
											{{ featured_post.tag.title }}
										</a>
										<span class="post-date">{{ featured_post.date_created|date:"M d, Y" }}</span>
									</div>
									<h3 class="post-title">
										<a href="{{ post.get_absolute_url }}">{{ featured_post.title }}</a>
									</h3>
								</div>
							</div>
						</div>

						{% for post in posts %}
						<div class="col-md-12">
							<div class="post post-row">
								<a class="post-img" href="{{ post.get_absolute_url }}">
									<img src="{{ post.image.url }}" alt="{{ post.title }}"></a>
								
									<div class="post-body">
									<div class="post-meta">
										<a class="post-category cat-2" href="{{ post.tag.get_absolute_url }}">
											{{ post.tag.title }}
										</a>
										<span class="post-date">{{ post.date_created|date:"M d, Y" }}</span>
									</div>
									<h3 class="post-title">
										<a href="{{ post.get_absolute_url }}">
											{{ post.title }}
										</a>
									</h3>
									<p>
										{{ post.content|truncatewords:25 }}
									</p>
								</div>
							</div>
						</div>
						{% endfor %}

					</div>
				</div>
				<div class="col-md-4">

					<div class="aside-widget">
						<div class="section-title">
							<h2>Most Read</h2>
						</div>

						{% for post in most_read_posts %}
						<div class="post post-widget">
							<a class="post-img" href="{{ post.get_absolute_url }}">
								<img src="{{ post.image.url }}" alt="{{ post.title }}"></a>
							
								<div class="post-body">
								<h3 class="post-title">
									<a href="{{ post.get_absolute_url }}">
										{{ post.title }}
									</a>
								</h3>
							</div>
						</div>
						{% endfor %}

					</div>

				</div>
			</div>

		</div>

	</div>
{% endblock %}

dynamo_blogger/templates/blog/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Home
{% endblock title %}

{% block content %}
<div class="section">

	<div class="container">

		<!-- Messages -->
		{% if messages %}
		<ul class="messages mobile__messages">
			{% for message in messages %}
			<li {% if message.tags %} class="alert alert-dark" {% endif %}>
				{{ message }}
			</li>
			{% endfor %}
		</ul>
		{% endif %}
		<!-- Messages -->

		<!-- Latest Updated Posts -->
		<div class="row">

			{% for post in latest_posts %}
			<div class="col-md-6">
				<div class="post post-thumb">
					<a class="post-img" href="{{ post.get_absolute_url }}">
						<img src="{{ post.image.url }}"
							alt="{{ post.title }}">
					</a>
					<div class="post-body">
						<div class="post-meta">
							<a class="post-category cat-2" href="{{ post.tag.get_absolute_url }}">
								{{ post.tag.title }}
							</a>
							<span class="post-date">{{ post.date_created|date:"M d, Y"  }}</span>
						</div>
						<h3 class="post-title">
							<a href="{{ post.get_absolute_url }}">
								{{ post.title }}
							</a>
						</h3>
					</div>
				</div>
			</div>
			{% endfor %}

		</div>

		<!-- Recent Posts -->
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h2>Recent Posts</h2>
				</div>
			</div>

			{% for post in recent_posts %}
			<div class="col-md-4">
				<div class="post">
					<a class="post-img" href="{{ post.get_absolute_url }}">
						<img src="{{ post.image.url }}" alt="{{ post.title }}">
					</a>
					<div class="post-body">
						<div class="post-meta">
							<a class="post-category cat-2" href="{{ post.tag.get_absolute_url }}">
								{{ post.tag.title }}
							</a>
							<span class="post-date">{{ post.date_created|date:"M d, Y"  }}</span>
						</div>
						<h3 class="post-title">
							<a href="{{ post.get_absolute_url }}">
								{{ post.title }}
							</a>
						</h3>
					</div>
				</div>
			</div>
			{% endfor %}

			<div class="clearfix visible-md visible-lg"></div>

		</div>


		<div class="row">
			<div class="col-md-8">
				<div class="row">

					{% for post in posts_1 %}
					<div class="col-md-12">
						<div class="post post-thumb">
							<a class="post-img" href="{{ post.get_absolute_url }}">
								<img src="{{ post.image.url }}" alt="{{ post.title }}">
							</a>

							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-2" href="{{ post.tag.get_absolute_url }}">
										{{ post.tag.title }}
									</a>
									<span class="post-date">{{ post.date_created|date:"M d, Y"  }}</span>
								</div>
								<h3 class="post-title">
									<a href="{{ post.get_absolute_url }}">
										{{ post.title }}
									</a>
								</h3>
							</div>
						</div>
					</div>
					{% endfor %}


					{% for post in posts_2 %}
					<div class="col-md-6">
						<div class="post">
							<a class="post-img" href="{{ post.get_absolute_url }}">
								<img src="{{ post.image.url }}" alt="{{ post.title }}">
							</a>

							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-4" href="{{ post.tag.get_absolute_url }}">
										{{ post.tag.title }}
									</a>
									<span class="post-date">{{ post.date_created|date:"M d, Y" }}</span>
								</div>
								<h3 class="post-title">
									<a href="{{ post.get_absolute_url }}">
										{{ post.title }}
									</a>
								</h3>
							</div>
						</div>
					</div>
					{% endfor %}

					<div class="clearfix visible-md visible-lg"></div>

					{% for post in posts_3 %}
					<div class="col-md-6">
						<div class="post">
							<a class="post-img" href="{{ post.get_absolute_url }}">
								<img src="{{ post.image.url }}" alt="{{ post.title }}">
							</a>

							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-4" href="{{ post.tag.get_absolute_url }}">
										{{ post.tag.title }}
									</a>
									<span class="post-date">{{ post.date_created|date:"M d, Y" }}</span>
								</div>
								<h3 class="post-title">
									<a href="{{ post.get_absolute_url }}">
										{{ post.title }}
									</a>
								</h3>
							</div>
						</div>
					</div>
					{% endfor %} 

					<div class="clearfix visible-md visible-lg"></div>
					
					{% for post in posts_4 %}
					<div class="col-md-6">
						<div class="post">
							<a class="post-img" href="{{ post.get_absolute_url }}">
								<img src="{{ post.image.url }}" alt="{{ post.title }}">
							</a>

							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-4" href="{{ post.tag.get_absolute_url }}">
										{{ post.tag.title }}
									</a>
									<span class="post-date">{{ post.date_created|date:"M d, Y" }}</span>
								</div>
								<h3 class="post-title">
									<a href="{{ post.get_absolute_url }}">
										{{ post.title }}
									</a>
								</h3>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>
			</div>
			<div class="col-md-4">

				<div class="aside-widget">
					<div class="section-title">
						<h2>Most Read</h2>
					</div>
					
					{% for post in most_read_posts %}
					<div class="post post-widget">
						<a class="post-img" href="{{ post.get_absolute_url }}">
							<img src="{{ post.image.url }}" alt="{{ post.title }}">
						</a>
						<div class="post-body">
							<h3 class="post-title">
								<a href="{{ post.get_absolute_url }}">
									{{ post.title }}
								</a>
							</h3>
						</div>
					</div>
					{% endfor %}
					
				</div>


				<div class="aside-widget">
					<div class="section-title">
						<h2>Featured Posts</h2>
					</div>


					{% for post in featured_posts %}
					<div class="post post-thumb">
						<a class="post-img" href="{{ post.get_absolute_url }}">
							<img src="{{ post.image.url }}" alt="{{ post.title }}">
						</a>
						
						<div class="post-body">
							<div class="post-meta">
								<a class="post-category cat-3" href="{{ post.tag.get_absolute_url }}">
									{{ post.tag.title }}
								</a>
								<span class="post-date">
									{{ post.date_created|date:"M d, Y" }}
								</span>
							</div>
							<h3 class="post-title">
								<a href="{{ post.get_absolute_url }}">
									{{ post.title }}
								</a>
							</h3>
						</div>
					</div>
					{% endfor %}
					
				</div>

			</div>
		</div>

	</div>

</div>

{% endblock content %}